#page title boop
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1612179432                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : us                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Tile flipping puzzle game

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Austin Jackson                               
your_link                                 : https://austinj.net                   
your_city                                 : Houston                                
email_address                             : austinjckson@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           : au5ton
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Accurate Gameplay
    description                           : Bomb Flip faithfully recreates the gameplay mechanics found in <a href="https://bulbapedia.bulbagarden.net/wiki/Voltorb_Flip">similar, classic mobile games</a>.
    # Pokémon HeartGold and SoulSilver
    # Inspired by Voltorb Flip from Pokémon HeartGold and SoulSilver, Bomb Flip is a faithful recreation of the gameplay mechanics found in the original.
    fontawesome_icon_name                 : gamepad

  - title                                 : Item Shop
    description                           : Using Coins earned from gameplay (and daily giveaways), unique items can be purchased to make gameplay more interesting
    fontawesome_icon_name                 : shop

  - title                                 : Modernized for iOS
    description                           : Adapted for comfortable gameplay on iOS, Bomb Flip is made using SwiftUI and SpriteKit
    fontawesome_icon_name                 : mobile

  - title                                 : Haptics-backed SFX
    description                           : Included Sound Effects with Haptic Feedback will amplify your nostalgia
    fontawesome_icon_name                 : file-audio
  
  - title                                 : Original Soundtrack
    description                           : Original Soundtrack produced by <a href="https://socksedm.com/">socks.</a> will bring you back to the <a href="https://bulbapedia.bulbagarden.net/wiki/Game_Corner">Game Corner</a>.
    fontawesome_icon_name                 : music

  - title                                 : GameCenter Integration
    description                           : Compete on multiple global leaderboards and unlock unique Ribbons (Achievements) to commemorate your accomplishments.
    fontawesome_icon_name                 : trophy

  - title                                 : Guide Included
    description                           : New to Bomb Flip? A comprehensive Help section is included to help get you on your feet.
    fontawesome_icon_name                 : info-circle

  - title                                 : iCloud Sync
    description                           : Progress throughout the game is automatically saved to iCloud and synced to your other devices
    fontawesome_icon_name                 : sync

  - title                                 : No ads or in-app purchases
    description                           : You are not the product, the app is. Buy once and keep forever.
    fontawesome_icon_name                 : ban

  - title                                 : iPad + Apple Silicon support
    description                           : iPads and Apple Silicon Macs are supported and welcome. (Native apps coming soon)
    fontawesome_icon_name                 : laptop

  - title                                 : Indie Developed
    description                           : Hi! That's me. I hope you like my app.
    fontawesome_icon_name                 : user

  # - title                                 : GitHub Pages Jekyll Theme
  #   description                           : Designed for GitHub Pages. Fork. Edit _config.yml. Upload screenshot/video. Push to gh-pages branch. Voilá!
  #   fontawesome_icon_name                 : magic
    
  # - title                                 : iPhone Device Preview
  #   description                           : Preview your app in the context of an iPhone device. Five different device colors included.
  #   fontawesome_icon_name                 : mobile

  # - title                                 : Video Support
  #   description                           : Preview app video on the iPhone device simply by placing your video files in the videos folder.
  #   fontawesome_icon_name                 : play-circle

  # - title                                 : Automatic Icon and Metadata
  #   description                           : Enter iOS app ID in the _config.yml file to automatically fetch app icon, price and App Store Link.
  #   fontawesome_icon_name                 : sync

  # - title                                 : Easy to Tweak
  #   description                           : Tweak accent color, images, icons and transparency via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : adjust
  
  # - title                                 : Feature List
  #   description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : star

  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down

  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link

  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.5

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
